#!/bin/bash

GREEN="\033[01;32m"
RESET="\033[00m"

echo -e "${GREEN}[>]${RESET} Updating OpenVAS feeds"

echo -e "${GREEN}[*]${RESET} [1/3] Updating: NVT"
greenbone-nvt-sync

echo -e "${GREEN}[*]${RESET} [2/3] Updating: Scap Data"
greenbone-scapdata-sync

echo -e "${GREEN}[*]${RESET} [3/3] Updating: Cert Data"
greenbone-certdata-sync

